@baseUrl = http://localhost:3000/api
@recipeId = cm3wb68yz0005ompfh3oe4enz

### Get Recipe by ID
GET {{baseUrl}}/recipes/{{recipeId}}

### Get Recipe details by ID
GET {{baseUrl}}/recipes/{{recipeId}}/details

### Get Recipes
GET {{baseUrl}}/recipes


@query = taco
@ingredients = 1,2,3
@blacklistedIngredients = 4,5,6
@ignoreBlacklistedIngredients = true

### Get Recipes with query
GET {{baseUrl}}/recipes?query={{query}}&ingredients={{ingredients}}&ignoreBlacklistedIngredients={{ignoreBlacklistedIngredients}}

### Get Recipes with query
GET {{baseUrl}}/recipes?query={{query}}&ignoreBlacklistedIngredients={{ignoreBlacklistedIngredients}}

